"function"!=typeof DIL&&(DIL=function(a,b){var d=[],c,e;a!==Object(a)&&(a={});var f,g,k,r,t,n,u,D,m,z,H;f=a.partner;g=a.containerNSID;k=a.iframeAttachmentDelay;r=!!a.disableDestinationPublishingIframe;t=a.iframeAkamaiHTTPS;n=a.mappings;u=a.uuidCookie;D=!0===a.enableErrorReporting;m=a.visitorService;z=a.declaredId;H=!0===a.removeFinishedScriptsAndCallbacks;var I,J,E,B;I=!0===a.disableScriptAttachment;J=!0===a.disableDefaultRequest;E=a.afterResultForDefaultRequest;B=a.dpIframeSrc;D&&DIL.errorModule.activate();
var K=!0===window._dil_unit_tests;(c=b)&&d.push(c+"");if(!f||"string"!=typeof f)return c="DIL partner is invalid or not specified in initConfig",DIL.errorModule.handleError({name:"error",message:c,filename:"dil.js"}),Error(c);c="DIL containerNSID is invalid or not specified in initConfig, setting to default of 0";if(g||"number"==typeof g)g=parseInt(g,10),!isNaN(g)&&0<=g&&(c="");c&&(g=0,d.push(c),c="");e=DIL.getDil(f,g);if(e instanceof DIL&&e.api.getPartner()==f&&e.api.getContainerNSID()==g)return e;
if(this instanceof DIL)DIL.registerDil(this,f,g);else return new DIL(a,"DIL was not instantiated with the 'new' operator, returning a valid instance with partner = "+f+" and containerNSID = "+g);var w={IS_HTTPS:"https:"==document.location.protocol,POST_MESSAGE_ENABLED:!!window.postMessage,COOKIE_MAX_EXPIRATION_DATE:"Tue, 19 Jan 2038 03:14:07 UTC"},F={stuffed:{}},l={},p={firingQueue:[],fired:[],firing:!1,sent:[],errored:[],reservedKeys:{sids:!0,pdata:!0,logdata:!0,callback:!0,postCallbackFn:!0,useImageRequest:!0},
callbackPrefix:"demdexRequestCallback",firstRequestHasFired:!1,useJSONP:!0,abortRequests:!1,num_of_jsonp_responses:0,num_of_jsonp_errors:0,num_of_img_responses:0,num_of_img_errors:0,toRemove:[],removed:[],readyToRemove:!1,platformParams:{d_nsid:g+"",d_rtbd:"json",d_jsonv:DIL.jsonVersion+"",d_dst:"1"},nonModStatsParams:{d_rtbd:!0,d_dst:!0,d_cts:!0,d_rs:!0},modStatsParams:null,adms:{TIME_TO_CATCH_ALL_REQUESTS_RELEASE:2E3,calledBack:!1,mid:null,noVisitorAPI:!1,instance:null,releaseType:"no VisitorAPI",
admsProcessingStarted:!1,process:function(h){try{if(!this.admsProcessingStarted){var a=this,v,b,c,d,f;if("function"==typeof h&&"function"==typeof h.getInstance){if(m===Object(m)&&(v=m.namespace)&&"string"==typeof v)b=h.getInstance(v);else{this.releaseType="no namespace";this.releaseRequests();return}if(b===Object(b)&&"function"==typeof b.isAllowed&&"function"==typeof b.getMarketingCloudVisitorID){if(!b.isAllowed()){this.releaseType="VisitorAPI not allowed";this.releaseRequests();return}this.instance=
b;this.admsProcessingStarted=!0;c=function(h){"VisitorAPI"!=a.releaseType&&(a.mid=h,a.releaseType="VisitorAPI",a.releaseRequests())};K&&(d=m.server)&&"string"==typeof d&&(b.server=d);f=b.getMarketingCloudVisitorID(c);if("string"==typeof f&&f.length){c(f);return}setTimeout(function(){"VisitorAPI"!=a.releaseType&&(a.releaseType="timeout",a.releaseRequests())},this.TIME_TO_CATCH_ALL_REQUESTS_RELEASE);return}this.releaseType="invalid instance"}else this.noVisitorAPI=!0;this.releaseRequests()}}catch(e){this.releaseRequests()}},
releaseRequests:function(){this.calledBack=!0;p.registerRequest()},getMarketingCloudVisitorID:function(){return this.instance?this.instance.getMarketingCloudVisitorID():null},getMIDQueryString:function(){var h=s.isPopulatedString,a=this.getMarketingCloudVisitorID();h(this.mid)&&this.mid==a||(this.mid=a);return h(this.mid)?"d_mid="+this.mid+"&":""}},declaredId:{declaredId:{init:null,request:null},declaredIdCombos:{},setDeclaredId:function(h,a){var b=s.isPopulatedString,c=encodeURIComponent;if(h===
Object(h)&&b(a)){var d=h.dpid,f=h.dpuuid,e=null;if(b(d)&&b(f)){e=c(d)+"$"+c(f);if(!0===this.declaredIdCombos[e])return"setDeclaredId: combo exists for type '"+a+"'";this.declaredIdCombos[e]=!0;this.declaredId[a]={dpid:d,dpuuid:f};return"setDeclaredId: succeeded for type '"+a+"'"}}return"setDeclaredId: failed for type '"+a+"'"},getDeclaredIdQueryString:function(){var h=this.declaredId.request,a=this.declaredId.init,b="";null!==h?b="&d_dpid="+h.dpid+"&d_dpuuid="+h.dpuuid:null!==a&&(b="&d_dpid="+a.dpid+
"&d_dpuuid="+a.dpuuid);return b}},registerRequest:function(h){var a=this.firingQueue;h===Object(h)&&a.push(h);!this.firing&&a.length&&(this.adms.calledBack?(h=a.shift(),h.src=h.src.replace(/demdex.net\/event\?d_nsid=/,"demdex.net/event?"+this.adms.getMIDQueryString()+"d_nsid="),x.fireRequest(h),this.firstRequestHasFired||"script"!=h.tag||(this.firstRequestHasFired=!0)):this.processVisitorAPI())},processVisitorAPI:function(){this.adms.process(window.Visitor)},requestRemoval:function(h){if(!H)return"removeFinishedScriptsAndCallbacks is not boolean true";
var a=this.toRemove,b,c;h===Object(h)&&(b=h.script,c=h.callbackName,(b===Object(b)&&"SCRIPT"==b.nodeName||"no script created"==b)&&"string"==typeof c&&c.length&&a.push(h));if(this.readyToRemove&&a.length){c=a.shift();b=c.script;c=c.callbackName;"no script created"!=b?(h=b.src,b.parentNode.removeChild(b)):h=b;window[c]=null;try{delete window[c]}catch(d){}this.removed.push({scriptSrc:h,callbackName:c});DIL.variables.scriptsRemoved.push(h);DIL.variables.callbacksRemoved.push(c);return this.requestRemoval()}return"requestRemoval() processed"}};
e=function(){var h="http://fast.",a="?d_nsid="+g+"#"+encodeURIComponent(document.location.href);if("string"===typeof B&&B.length)return B+a;w.IS_HTTPS&&(h=!0===t?"https://fast.":"https://");return h+f+".demdex.net/dest4.html"+a};var y={THROTTLE_START:3E4,throttleTimerSet:!1,id:"destination_publishing_iframe_"+f+"_"+g,url:e(),iframe:null,iframeHasLoaded:!1,sendingMessages:!1,messages:[],messagesPosted:[],messageSendingInterval:w.POST_MESSAGE_ENABLED?15:100,jsonProcessed:[],attachIframe:function(){var h=
this,a=document.createElement("iframe");a.id=this.id;a.style.cssText="display: none; width: 0; height: 0;";a.src=this.url;q.addListener(a,"load",function(){h.iframeHasLoaded=!0;h.requestToProcess()});document.body.appendChild(a);this.iframe=a},requestToProcess:function(h,a){var b=this;h&&!s.isEmptyObject(h)&&this.process(h,a);this.iframeHasLoaded&&this.messages.length&&!this.sendingMessages&&(this.throttleTimerSet||(this.throttleTimerSet=!0,setTimeout(function(){b.messageSendingInterval=w.POST_MESSAGE_ENABLED?
15:150},this.THROTTLE_START)),this.sendingMessages=!0,this.sendMessages())},process:function(h,a){var b=encodeURIComponent,c,d,f,e,g,m;a===Object(a)&&(m=q.encodeAndBuildRequest(["",a.dpid||"",a.dpuuid||""],","));if((c=h.dests)&&c instanceof Array&&(d=c.length))for(f=0;f<d;f++)e=c[f],e=[b("dests"),b(e.id||""),b(e.y||""),b(e.c||"")],this.addMessage(e.join("|"));if((c=h.ibs)&&c instanceof Array&&(d=c.length))for(f=0;f<d;f++)e=c[f],e=[b("ibs"),b(e.id||""),b(e.tag||""),q.encodeAndBuildRequest(e.url||[],
","),b(e.ttl||""),"",m],this.addMessage(e.join("|"));if((c=h.dpcalls)&&c instanceof Array&&(d=c.length))for(f=0;f<d;f++)e=c[f],g=e.callback||{},g=[g.obj||"",g.fn||"",g.key||"",g.tag||"",g.url||""],e=[b("dpm"),b(e.id||""),b(e.tag||""),q.encodeAndBuildRequest(e.url||[],","),b(e.ttl||""),q.encodeAndBuildRequest(g,","),m],this.addMessage(e.join("|"));this.jsonProcessed.push(h)},addMessage:function(h){var a=encodeURIComponent,a=D?a("---destpub-debug---"):a("---destpub---");this.messages.push(a+h)},sendMessages:function(){var h=
this,a;this.messages.length?(a=this.messages.shift(),DIL.xd.postMessage(a,this.url,this.iframe.contentWindow),this.messagesPosted.push(a),setTimeout(function(){h.sendMessages()},this.messageSendingInterval)):this.sendingMessages=!1}},G={traits:function(h){s.isValidPdata(h)&&(l.sids instanceof Array||(l.sids=[]),q.extendArray(l.sids,h));return this},pixels:function(h){s.isValidPdata(h)&&(l.pdata instanceof Array||(l.pdata=[]),q.extendArray(l.pdata,h));return this},logs:function(h){s.isValidLogdata(h)&&
(l.logdata!==Object(l.logdata)&&(l.logdata={}),q.extendObject(l.logdata,h));return this},customQueryParams:function(h){s.isEmptyObject(h)||q.extendObject(l,h,p.reservedKeys);return this},signals:function(h,a){var b,c=h;if(!s.isEmptyObject(c)){if(a&&"string"==typeof a)for(b in c={},h)h.hasOwnProperty(b)&&(c[a+b]=h[b]);q.extendObject(l,c,p.reservedKeys)}return this},declaredId:function(h){p.declaredId.setDeclaredId(h,"request");return this},result:function(h){"function"==typeof h&&(l.callback=h);return this},
afterResult:function(h){"function"==typeof h&&(l.postCallbackFn=h);return this},useImageRequest:function(){l.useImageRequest=!0;return this},clearData:function(){l={};return this},submit:function(){x.submitRequest(l);l={};return this},getPartner:function(){return f},getContainerNSID:function(){return g},getEventLog:function(){return d},getState:function(){var h={},a={};q.extendObject(h,p,{callbackPrefix:!0,useJSONP:!0,registerRequest:!0});q.extendObject(a,y,{attachIframe:!0,requestToProcess:!0,process:!0,
sendMessages:!0});return{pendingRequest:l,otherRequestInfo:h,destinationPublishingInfo:a}},idSync:function(a){if(a!==Object(a)||"string"!=typeof a.dpid||!a.dpid.length)return"Error: config or config.dpid is empty";if("string"!=typeof a.url||!a.url.length)return"Error: config.url is empty";var b=a.url,c=a.minutesToLive,d=encodeURIComponent,f,b=b.replace(/^https:/,"").replace(/^http:/,"");if("undefined"==typeof c)c=20160;else if(c=parseInt(c,10),isNaN(c)||0>=c)return"Error: config.minutesToLive needs to be a positive number";
f=q.encodeAndBuildRequest(["",a.dpid,a.dpuuid||""],",");a=["ibs",d(a.dpid),"img",d(b),c,"",f];y.addMessage(a.join("|"));p.firstRequestHasFired&&y.requestToProcess();return"Successfully queued"},aamIdSync:function(a){if(a!==Object(a)||"string"!=typeof a.dpuuid||!a.dpuuid.length)return"Error: config or config.dpuuid is empty";a.url="//dpm.demdex.net/ibs:dpid="+a.dpid+"&dpuuid="+a.dpuuid;return this.idSync(a)},passData:function(a){if(s.isEmptyObject(a))return"Error: json is empty or not an object";x.defaultCallback(a);
return"json submitted for processing"},getPlatformParams:function(){return p.platformParams},getEventCallConfigParams:function(){var a=p,b=a.modStatsParams,c=a.platformParams,d;if(!b){b={};for(d in c)c.hasOwnProperty(d)&&!a.nonModStatsParams[d]&&(b[d.replace(/^d_/,"")]=c[d]);a.modStatsParams=b}return b}},x={submitRequest:function(a){p.registerRequest(x.createQueuedRequest(a));return!0},createQueuedRequest:function(a){var b=p,c,d=a.callback,e="img";if(!s.isEmptyObject(n)){var A,m,u;for(A in n)n.hasOwnProperty(A)&&
(m=n[A],null!=m&&""!==m&&A in a&&!(m in a||m in p.reservedKeys)&&(u=a[A],null!=u&&""!==u&&(a[m]=u)))}s.isValidPdata(a.sids)||(a.sids=[]);s.isValidPdata(a.pdata)||(a.pdata=[]);s.isValidLogdata(a.logdata)||(a.logdata={});a.logdataArray=q.convertObjectToKeyValuePairs(a.logdata,"=",!0);a.logdataArray.push("_ts="+(new Date).getTime());"function"!=typeof d&&(d=this.defaultCallback);if(b.useJSONP=!a.useImageRequest||"boolean"!=typeof a.useImageRequest)e="script",c=b.callbackPrefix+"_"+f+"_"+g+"_"+(new Date).getTime();
return{tag:e,src:x.makeRequestSrc(a,c),internalCallbackName:c,callbackFn:d,postCallbackFn:a.postCallbackFn,useImageRequest:a.useImageRequest,requestData:a}},defaultCallback:function(a,b){var c,d,f,e,g,m,n,l,k;if((c=a.stuff)&&c instanceof Array&&(d=c.length))for(f=0;f<d;f++)if((e=c[f])&&e===Object(e)){g=e.cn;m=e.cv;n=e.ttl;if("undefined"==typeof n||""===n)n=Math.floor(q.getMaxCookieExpiresInMinutes()/60/24);l=e.dmn||"."+document.domain.replace(/^www\./,"");k=e.type;g&&(m||"number"==typeof m)&&("var"!=
k&&(n=parseInt(n,10))&&!isNaN(n)&&q.setCookie(g,m,1440*n,"/",l,!1),F.stuffed[g]=m)}c=a.uuid;s.isPopulatedString(c)&&!s.isEmptyObject(u)&&(d=u.path,"string"==typeof d&&d.length||(d="/"),f=parseInt(u.days,10),isNaN(f)&&(f=100),q.setCookie(u.name||"aam_did",c,1440*f,d,u.domain||"."+document.domain.replace(/^www\./,""),!0===u.secure));r||p.abortRequests||y.requestToProcess(a,b)},makeRequestSrc:function(a,b){a.sids=s.removeEmptyArrayValues(a.sids||[]);a.pdata=s.removeEmptyArrayValues(a.pdata||[]);var c=
p,d=c.platformParams,e=q.encodeAndBuildRequest(a.sids,","),g=q.encodeAndBuildRequest(a.pdata,","),m=(a.logdataArray||[]).join("&");delete a.logdataArray;var n=w.IS_HTTPS?"https://":"http://",u=c.declaredId.getDeclaredIdQueryString(),l;l=[];var k,t,r,z;for(k in a)if(!(k in c.reservedKeys)&&a.hasOwnProperty(k))if(t=a[k],k=encodeURIComponent(k),t instanceof Array)for(r=0,z=t.length;r<z;r++)l.push(k+"="+encodeURIComponent(t[r]));else l.push(k+"="+encodeURIComponent(t));l=l.length?"&"+l.join("&"):"";return n+
f+".demdex.net/event?d_nsid="+d.d_nsid+u+(e.length?"&d_sid="+e:"")+(g.length?"&d_px="+g:"")+(m.length?"&d_ld="+encodeURIComponent(m):"")+l+(c.useJSONP?"&d_rtbd="+d.d_rtbd+"&d_jsonv="+d.d_jsonv+"&d_dst="+d.d_dst+"&d_cb="+(b||""):"")},fireRequest:function(a){if("img"==a.tag)this.fireImage(a);else if("script"==a.tag){var b=p.declaredId,b=b.declaredId.request||b.declaredId.init||{};this.fireScript(a,{dpid:b.dpid||"",dpuuid:b.dpuuid||""})}},fireImage:function(a){var b=p,f,e;b.abortRequests||(b.firing=
!0,f=new Image(0,0),b.sent.push(a),f.onload=function(){b.firing=!1;b.fired.push(a);b.num_of_img_responses++;b.registerRequest()},e=function(f){c="imgAbortOrErrorHandler received the event of type "+f.type;d.push(c);b.abortRequests=!0;b.firing=!1;b.errored.push(a);b.num_of_img_errors++;b.registerRequest()},f.addEventListener?(f.addEventListener("error",e,!1),f.addEventListener("abort",e,!1)):f.attachEvent&&(f.attachEvent("onerror",e),f.attachEvent("onabort",e)),f.src=a.src)},fireScript:function(a,
b){var e=this,g=p,m,n,u=a.src,k=a.postCallbackFn,l="function"==typeof k,t=a.internalCallbackName;g.abortRequests||(g.firing=!0,window[t]=function(e){try{e!==Object(e)&&(e={});var m=a.callbackFn;g.firing=!1;g.fired.push(a);g.num_of_jsonp_responses++;m(e,b);l&&k(e,b)}catch(v){v.message="DIL jsonp callback caught error with message "+v.message;c=v.message;d.push(c);v.filename=v.filename||"dil.js";v.partner=f;DIL.errorModule.handleError(v);try{m({error:v.name+"|"+v.message}),l&&k({error:v.name+"|"+v.message})}catch(u){}}finally{g.requestRemoval({script:n,
callbackName:t}),g.registerRequest()}},I?(g.firing=!1,g.requestRemoval({script:"no script created",callbackName:t})):(n=document.createElement("script"),n.addEventListener&&n.addEventListener("error",function(b){g.requestRemoval({script:n,callbackName:t});c="jsonp script tag error listener received the event of type "+b.type+" with src "+u;e.handleScriptError(c,a)},!1),n.type="text/javascript",n.src=u,m=DIL.variables.scriptNodeList[0],m.parentNode.insertBefore(n,m)),g.sent.push(a),g.declaredId.declaredId.request=
null)},handleScriptError:function(a,b){var c=p;d.push(a);c.abortRequests=!0;c.firing=!1;c.errored.push(b);c.num_of_jsonp_errors++;c.registerRequest()}},s={isValidPdata:function(a){return a instanceof Array&&this.removeEmptyArrayValues(a).length?!0:!1},isValidLogdata:function(a){return!this.isEmptyObject(a)},isEmptyObject:function(a){if(a!==Object(a))return!0;for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},removeEmptyArrayValues:function(a){for(var b=0,c=a.length,d,e=[],b=0;b<c;b++)d=a[b],
"undefined"!=typeof d&&null!=d&&e.push(d);return e},isPopulatedString:function(a){return"string"==typeof a&&a.length}},q={addListener:function(){if(document.addEventListener)return function(a,b,c){a.addEventListener(b,function(a){"function"==typeof c&&c(a)},!1)};if(document.attachEvent)return function(a,b,c){a.attachEvent("on"+b,function(a){"function"==typeof c&&c(a)})}}(),convertObjectToKeyValuePairs:function(a,b,c){var d=[];b=b||"=";var e,f;for(e in a)f=a[e],"undefined"!=typeof f&&null!=f&&d.push(e+
b+(c?encodeURIComponent(f):f));return d},encodeAndBuildRequest:function(a,b){return this.map(a,function(a){return encodeURIComponent(a)}).join(b)},map:function(a,b){if(Array.prototype.map)return a.map(b);if(void 0===a||null===a)throw new TypeError;var c=Object(a),d=c.length>>>0;if("function"!==typeof b)throw new TypeError;for(var e=Array(d),f=0;f<d;f++)f in c&&(e[f]=b.call(b,c[f],f,c));return e},filter:function(a,b){if(!Array.prototype.filter){if(void 0===a||null===a)throw new TypeError;var c=Object(a),
d=c.length>>>0;if("function"!==typeof b)throw new TypeError;for(var f=[],e=0;e<d;e++)if(e in c){var g=c[e];b.call(b,g,e,c)&&f.push(g)}return f}return a.filter(b)},getCookie:function(a){a+="=";var b=document.cookie.split(";"),c,d,e;c=0;for(d=b.length;c<d;c++){for(e=b[c];" "==e.charAt(0);)e=e.substring(1,e.length);if(0==e.indexOf(a))return decodeURIComponent(e.substring(a.length,e.length))}return null},setCookie:function(a,b,c,d,e,f){var g=new Date;c&&(c*=6E4);document.cookie=a+"="+encodeURIComponent(b)+
(c?";expires="+(new Date(g.getTime()+c)).toUTCString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(f?";secure":"")},extendArray:function(a,b){return a instanceof Array&&b instanceof Array?(Array.prototype.push.apply(a,b),!0):!1},extendObject:function(a,b,c){var d;if(a===Object(a)&&b===Object(b)){for(d in b)!b.hasOwnProperty(d)||!s.isEmptyObject(c)&&d in c||(a[d]=b[d]);return!0}return!1},getMaxCookieExpiresInMinutes:function(){return((new Date(w.COOKIE_MAX_EXPIRATION_DATE)).getTime()-(new Date).getTime())/
1E3/60}};"error"==f&&0==g&&q.addListener(window,"load",function(){DIL.windowLoaded=!0});var C=function(){M();r||p.abortRequests||y.attachIframe();p.readyToRemove=!0;p.requestRemoval()},M=function(){r||setTimeout(function(){J||p.firstRequestHasFired||p.adms.admsProcessingStarted||p.adms.calledBack||("function"==typeof E?G.afterResult(E).submit():G.submit())},DIL.constants.TIME_TO_DEFAULT_REQUEST)},L=document;"error"!=f&&(DIL.windowLoaded?C():"complete"!=L.readyState&&"loaded"!=L.readyState?q.addListener(window,
"load",C):DIL.isAddedPostWindowLoadWasCalled?q.addListener(window,"load",C):(k="number"==typeof k?parseInt(k,10):0,0>k&&(k=0),setTimeout(C,k||DIL.constants.TIME_TO_CATCH_ALL_DP_IFRAME_ATTACHMENT)));p.declaredId.setDeclaredId(z,"init");this.api=G;this.getStuffedVariable=function(a){var b=F.stuffed[a];b||"number"==typeof b||(b=q.getCookie(a))||"number"==typeof b||(b="");return b};this.validators=s;this.helpers=q;this.constants=w;this.log=d;K&&(this.pendingRequest=l,this.requestController=p,this.setDestinationPublishingUrl=
e,this.destinationPublishing=y,this.requestProcs=x,this.variables=F)},function(){var a=document,b;null==a.readyState&&a.addEventListener&&(a.readyState="loading",a.addEventListener("DOMContentLoaded",b=function(){a.removeEventListener("DOMContentLoaded",b,!1);a.readyState="complete"},!1))}(),DIL.extendStaticPropertiesAndMethods=function(a){var b;if(a===Object(a))for(b in a)a.hasOwnProperty(b)&&(this[b]=a[b])},DIL.extendStaticPropertiesAndMethods({version:"5.0",jsonVersion:1,constants:{TIME_TO_DEFAULT_REQUEST:50,
TIME_TO_CATCH_ALL_DP_IFRAME_ATTACHMENT:500},variables:{scriptNodeList:document.getElementsByTagName("script"),scriptsRemoved:[],callbacksRemoved:[]},windowLoaded:!1,dils:{},isAddedPostWindowLoadWasCalled:!1,isAddedPostWindowLoad:function(a){this.isAddedPostWindowLoadWasCalled=!0;this.windowLoaded="function"==typeof a?!!a():"boolean"==typeof a?a:!0},create:function(a){try{return new DIL(a)}catch(b){return(new Image(0,0)).src="http://error.demdex.net/event?d_nsid=0&d_px=14137&d_ld=name%3Derror%26filename%3Ddil.js%26partner%3Dno_partner%26message%3DError%2520in%2520attempt%2520to%2520create%2520DIL%2520instance%2520with%2520DIL.create()%26_ts%3D"+
(new Date).getTime(),Error("Error in attempt to create DIL instance with DIL.create()")}},registerDil:function(a,b,d){b=b+"$"+d;b in this.dils||(this.dils[b]=a)},getDil:function(a,b){var d;"string"!=typeof a&&(a="");b||(b=0);d=a+"$"+b;return d in this.dils?this.dils[d]:Error("The DIL instance with partner = "+a+" and containerNSID = "+b+" was not found")},dexGetQSVars:function(a,b,d){b=this.getDil(b,d);return b instanceof this?b.getStuffedVariable(a):""},xd:{postMessage:function(a,b,d){var c=1;b&&
(window.postMessage?d.postMessage(a,b.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):b&&(d.location=b.replace(/#.*$/,"")+"#"+ +new Date+c++ +"&"+a))}}}),DIL.errorModule=function(){var a=DIL.create({partner:"error",containerNSID:0,disableDestinationPublishingIframe:!0}),b={harvestererror:14138,destpuberror:14139,dpmerror:14140,generalerror:14137,error:14137,noerrortypedefined:15021,evalerror:15016,rangeerror:15017,referenceerror:15018,typeerror:15019,urierror:15020},d=!1;return{activate:function(){d=!0},handleError:function(c){if(!d)return"DIL error module has not been activated";
c!==Object(c)&&(c={});var e=c.name?(new String(c.name)).toLowerCase():"",f=[];c={name:e,filename:c.filename?c.filename+"":"",partner:c.partner?c.partner+"":"no_partner",site:c.site?c.site+"":document.location.href,message:c.message?c.message+"":""};f.push(e in b?b[e]:b.noerrortypedefined);a.api.pixels(f).logs(c).useImageRequest().submit();return"DIL error report sent"},pixelMap:b}}(),DIL.tools={},DIL.modules={helpers:{handleModuleError:function(a,b,d){var c="";b=b||"Error caught in DIL module/submodule: ";
a===Object(a)?c=b+(a.message||"err has no message"):(c=b+"err is not a valid object",a={});a.message=c;d instanceof DIL&&(a.partner=d.api.getPartner());DIL.errorModule.handleError(a);return this.errorMessage=c}}});
DIL.tools.getSearchReferrer=function(a,b){var d=DIL.getDil("error"),c=DIL.tools.decomposeURI(a||document.referrer),e="",f="",g={queryParam:"q"};return(e=d.helpers.filter([b===Object(b)?b:{},{hostPattern:/aol\./},{hostPattern:/ask\./},{hostPattern:/bing\./},{hostPattern:/google\./},{hostPattern:/yahoo\./,queryParam:"p"}],function(a){return!(!a.hasOwnProperty("hostPattern")||!c.hostname.match(a.hostPattern))}).shift())?{valid:!0,name:c.hostname,keywords:(d.helpers.extendObject(g,e),f=g.queryPattern?
(e=(""+c.search).match(g.queryPattern))?e[1]:"":c.uriParams[g.queryParam],decodeURIComponent(f||"").replace(/\+|%20/g," "))}:{valid:!1,name:"",keywords:""}};
DIL.tools.decomposeURI=function(a){var b=DIL.getDil("error"),d=document.createElement("a");d.href=a||document.referrer;return{hash:d.hash,host:d.host.split(":").shift(),hostname:d.hostname,href:d.href,pathname:d.pathname.replace(/^\//,""),protocol:d.protocol,search:d.search,uriParams:function(a,d){b.helpers.map(d.split("&"),function(b){b=b.split("=");a[b.shift()]=b.shift()});return a}({},d.search.replace(/^(\/|\?)?|\/$/g,""))}};
DIL.tools.getMetaTags=function(){var a={},b=document.getElementsByTagName("meta"),d,c,e,f,g;d=0;for(e=arguments.length;d<e;d++)if(f=arguments[d],null!==f)for(c=0;c<b.length;c++)if(g=b[c],g.name==f){a[f]=g.content;break}return a};
DIL.modules.siteCatalyst={dil:null,handle:DIL.modules.helpers.handleModuleError,init:function(a,b,d,c){try{var e=this,f={name:"DIL Site Catalyst Module Error"},g=function(a){f.message=a;DIL.errorModule.handleError(f);return a};this.options=c===Object(c)?c:{};this.dil=null;if(b instanceof DIL)this.dil=b;else return g("dilInstance is not a valid instance of DIL");f.partner=b.api.getPartner();if(a!==Object(a))return g("siteCatalystReportingSuite is not an object");window.AppMeasurement_Module_DIL=a.m_DIL=
function(a){var b="function"===typeof a.m_i?a.m_i("DIL"):this;if(b!==Object(b))return g("m is not an object");b.trackVars=e.constructTrackVars(d);b.d=0;b.s=a;b._t=function(){var a,b,c=","+this.trackVars+",",d=this.s,f,k=[];f=[];var t={},r=!1;if(d!==Object(d))return g("Error in m._t function: s is not an object");if(this.d){if("function"==typeof d.foreachVar)d.foreachVar(function(a,b){t[a]=b;r=!0},this.trackVars);else{if(!(d.va_t instanceof Array))return g("Error in m._t function: s.va_t is not an array");
if(d.lightProfileID)(a=d.lightTrackVars)&&(a=","+a+","+d.vl_mr+",");else if(d.pe||d.linkType)a=d.linkTrackVars,d.pe&&(b=d.pe.substring(0,1).toUpperCase()+d.pe.substring(1),d[b]&&(a=d[b].trackVars)),a&&(a=","+a+","+d.vl_l+","+d.vl_l2+",");if(a){b=0;for(k=a.split(",");b<k.length;b++)0<=c.indexOf(","+k[b]+",")&&f.push(k[b]);f.length&&(c=","+f.join(",")+",")}f=0;for(b=d.va_t.length;f<b;f++)a=d.va_t[f],0<=c.indexOf(","+a+",")&&null!=d[a]&&""!==d[a]&&(t[a]=d[a],r=!0)}e.includeContextData(d,e,t).store_populated&&
(r=!0);r&&this.d.api.signals(t,"c_").submit()}}};a.loadModule("DIL");a.DIL.d=b;return f.message?f.message:"DIL.modules.siteCatalyst.init() completed with no errors"}catch(k){return this.handle(k,"DIL.modules.siteCatalyst.init() caught error with message ",this.dil)}},constructTrackVars:function(a){var b=[],d,c,e,f,g;if(a===Object(a)){d=a.names;if(d instanceof Array&&(e=d.length))for(c=0;c<e;c++)f=d[c],"string"==typeof f&&f.length&&b.push(f);a=a.iteratedNames;if(a instanceof Array&&(e=a.length))for(c=
0;c<e;c++)if(d=a[c],d===Object(d)&&(f=d.name,g=parseInt(d.maxIndex,10),"string"==typeof f&&f.length&&!isNaN(g)&&0<=g))for(d=0;d<=g;d++)b.push(f+d);if(b.length)return b.join(",")}return this.constructTrackVars({names:"pageName channel campaign products events pe pev1 pev2 pev3".split(" "),iteratedNames:[{name:"prop",maxIndex:75},{name:"eVar",maxIndex:75}]})},includeContextData:function(a,b,d){var c={},e=!1;if(a.contextData===Object(a.contextData)){a=a.contextData;b=b.options.replaceContextDataPeriodsWith;
var f,g;"string"===typeof b&&b.length||(b="_");for(f in a)a.hasOwnProperty(f)&&((g=a[f])||"number"===typeof g)&&(f=("contextData."+f).replace(/\./g,b),d[f]=g,e=!0)}c.store_populated=e;return c}};
DIL.modules.GA={dil:null,arr:null,tv:null,errorMessage:"",defaultTrackVars:["_setAccount","_setCustomVar","_addItem","_addTrans","_trackSocial"],defaultTrackVarsObj:null,signals:{},hasSignals:!1,handle:DIL.modules.helpers.handleModuleError,init:function(a,b,d){try{this.tv=this.arr=this.dil=null;this.errorMessage="";this.signals={};this.hasSignals=!1;var c={name:"DIL GA Module Error"},e="";b instanceof DIL?(this.dil=b,c.partner=this.dil.api.getPartner()):(e="dilInstance is not a valid instance of DIL",
c.message=e,DIL.errorModule.handleError(c));a instanceof Array&&a.length?this.arr=a:(e="gaArray is not an array or is empty",c.message=e,DIL.errorModule.handleError(c));this.tv=this.constructTrackVars(d);this.errorMessage=e}catch(f){this.handle(f,"DIL.modules.GA.init() caught error with message ",this.dil)}finally{return this}},constructTrackVars:function(a){var b=[],d,c,e,f;if(this.defaultTrackVarsObj!==Object(this.defaultTrackVarsObj)){e=this.defaultTrackVars;f={};d=0;for(c=e.length;d<c;d++)f[e[d]]=
!0;this.defaultTrackVarsObj=f}else f=this.defaultTrackVarsObj;if(a===Object(a)){a=a.names;if(a instanceof Array&&(c=a.length))for(d=0;d<c;d++)e=a[d],"string"==typeof e&&e.length&&e in f&&b.push(e);if(b.length)return b}return this.defaultTrackVars},constructGAObj:function(a){var b={};a=a instanceof Array?a:this.arr;var d,c,e,f;d=0;for(c=a.length;d<c;d++)e=a[d],e instanceof Array&&e.length&&(e=[],f=a[d],e instanceof Array&&f instanceof Array&&Array.prototype.push.apply(e,f),f=e.shift(),"string"==typeof f&&
f.length&&(b[f]instanceof Array||(b[f]=[]),b[f].push(e)));return b},addToSignals:function(a,b){if("string"!=typeof a||""===a||null==b||""===b)return!1;this.signals[a]instanceof Array||(this.signals[a]=[]);this.signals[a].push(b);return this.hasSignals=!0},constructSignals:function(){var a=this.constructGAObj(),b={_setAccount:function(a){this.addToSignals("c_accountId",a)},_setCustomVar:function(a,b,c,d){"string"==typeof b&&b.length&&this.addToSignals("c_"+b,c)},_addItem:function(a,b,c,d,e,f){this.addToSignals("c_itemOrderId",
a);this.addToSignals("c_itemSku",b);this.addToSignals("c_itemName",c);this.addToSignals("c_itemCategory",d);this.addToSignals("c_itemPrice",e);this.addToSignals("c_itemQuantity",f)},_addTrans:function(a,b,c,d,e,f,g,k){this.addToSignals("c_transOrderId",a);this.addToSignals("c_transAffiliation",b);this.addToSignals("c_transTotal",c);this.addToSignals("c_transTax",d);this.addToSignals("c_transShipping",e);this.addToSignals("c_transCity",f);this.addToSignals("c_transState",g);this.addToSignals("c_transCountry",
k)},_trackSocial:function(a,b,c,d){this.addToSignals("c_socialNetwork",a);this.addToSignals("c_socialAction",b);this.addToSignals("c_socialTarget",c);this.addToSignals("c_socialPagePath",d)}},d=this.tv,c,e,f,g,k,r;c=0;for(e=d.length;c<e;c++)if(f=d[c],a.hasOwnProperty(f)&&b.hasOwnProperty(f)&&(r=a[f],r instanceof Array))for(g=0,k=r.length;g<k;g++)b[f].apply(this,r[g])},submit:function(){try{if(""!==this.errorMessage)return this.errorMessage;this.constructSignals();return this.hasSignals?(this.dil.api.signals(this.signals).submit(),
"Signals sent: "+this.dil.helpers.convertObjectToKeyValuePairs(this.signals,"=",!0)+this.dil.log):"No signals present"}catch(a){return this.handle(a,"DIL.modules.GA.submit() caught error with message ",this.dil)}},Stuffer:{LIMIT:5,dil:null,cookieName:null,delimiter:null,errorMessage:"",handle:DIL.modules.helpers.handleModuleError,callback:null,v:function(){return!1},init:function(a,b,d){try{this.callback=this.dil=null,this.errorMessage="",a instanceof DIL?(this.dil=a,this.v=this.dil.validators.isPopulatedString,
this.cookieName=this.v(b)?b:"aam_ga",this.delimiter=this.v(d)?d:"|"):this.handle({message:"dilInstance is not a valid instance of DIL"},"DIL.modules.GA.Stuffer.init() error: ")}catch(c){this.handle(c,"DIL.modules.GA.Stuffer.init() caught error with message ",this.dil)}finally{return this}},process:function(a){var b,d,c,e,f,g;g=!1;var k=1;if(a===Object(a)&&(b=a.stuff)&&b instanceof Array&&(d=b.length))for(a=0;a<d;a++)if((c=b[a])&&c===Object(c)&&(e=c.cn,f=c.cv,e==this.cookieName&&this.v(f))){g=!0;break}if(g){b=
f.split(this.delimiter);"undefined"==typeof window._gaq&&(window._gaq=[]);c=window._gaq;a=0;for(d=b.length;a<d&&!(g=b[a].split("="),f=g[0],g=g[1],this.v(f)&&this.v(g)&&c.push(["_setCustomVar",k++,f,g,1]),k>this.LIMIT);a++);this.errorMessage=1<k?"No errors - stuffing successful":"No valid values to stuff"}else this.errorMessage="Cookie name and value not found in json";if("function"==typeof this.callback)return this.callback()},submit:function(){try{var a=this;if(""!==this.errorMessage)return this.errorMessage;
this.dil.api.afterResult(function(b){a.process(b)}).submit();return"DIL.modules.GA.Stuffer.submit() successful"}catch(b){return this.handle(b,"DIL.modules.GA.Stuffer.submit() caught error with message ",this.dil)}}}};
DIL.modules.Peer39={aid:"",dil:null,optionals:null,errorMessage:"",calledBack:!1,script:null,scriptsSent:[],returnedData:[],handle:DIL.modules.helpers.handleModuleError,init:function(a,b,d){try{this.dil=null;this.errorMessage="";this.calledBack=!1;this.optionals=d===Object(d)?d:{};d={name:"DIL Peer39 Module Error"};var c=[],e="";this.isSecurePageButNotEnabled(document.location.protocol)&&(e="Module has not been enabled for a secure page",c.push(e),d.message=e,DIL.errorModule.handleError(d));b instanceof
DIL?(this.dil=b,d.partner=this.dil.api.getPartner()):(e="dilInstance is not a valid instance of DIL",c.push(e),d.message=e,DIL.errorModule.handleError(d));"string"==typeof a&&a.length?this.aid=a:(e="aid is not a string or is empty",c.push(e),d.message=e,DIL.errorModule.handleError(d));this.errorMessage=c.join("\n")}catch(f){this.handle(f,"DIL.modules.Peer39.init() caught error with message ",this.dil)}finally{return this}},isSecurePageButNotEnabled:function(a){return"https:"==a&&!0!==this.optionals.enableHTTPS?
!0:!1},constructSignals:function(){var a=this,b=this.constructScript(),d=DIL.variables.scriptNodeList[0];window["afterFinished_"+this.aid]=function(){try{var b=a.processData(p39_KVP_Short("c_p","|").split("|"));b.hasSignals&&a.dil.api.signals(b.signals).submit()}catch(d){}finally{a.calledBack=!0,"function"==typeof a.optionals.afterResult&&a.optionals.afterResult()}};d.parentNode.insertBefore(b,d);this.scriptsSent.push(b);return"Request sent to Peer39"},processData:function(a){var b,d,c,e,f={},g=!1;
this.returnedData.push(a);if(a instanceof Array)for(b=0,d=a.length;b<d;b++)c=a[b].split("="),e=c[0],c=c[1],e&&isFinite(c)&&!isNaN(parseInt(c,10))&&(f[e]instanceof Array||(f[e]=[]),f[e].push(c),g=!0);return{hasSignals:g,signals:f}},constructScript:function(){var a=document.createElement("script"),b=this.optionals,d=b.scriptId,c=b.scriptSrc,b=b.scriptParams;a.id="string"==typeof d&&d.length?d:"peer39ScriptLoader";a.type="text/javascript";"string"==typeof c&&c.length?a.src=c:(a.src=(this.dil.constants.IS_HTTPS?
"https:":"http:")+"//stags.peer39.net/"+this.aid+"/trg_"+this.aid+".js","string"==typeof b&&b.length&&(a.src+="?"+b));return a},submit:function(){try{return""!==this.errorMessage?this.errorMessage:this.constructSignals()}catch(a){return this.handle(a,"DIL.modules.Peer39.submit() caught error with message ",this.dil)}}};


var axDil = DIL.create({
	partner: 'aexp',
	containerNSID: 15
});
var _scDilObj;
if(typeof s != 'undefined' && s === Object(s) && typeof s.account != 'undefined' && s.account){
	_scDilObj = s_gi(s.account);
} else {
	_scDilObj = s_gi(s_account);
}


DIL.modules.siteCatalyst.init(_scDilObj, axDil, {
		names: ['pageName', 'channel', 'campaign', 'products', 'events', 'pe', 'referrer', 'server', 'purchaseID', 'zip', 'state'],
		iteratedNames: [{
			name: 'eVar',
			maxIndex: 75
		}, {
			name: 'prop',
			maxIndex: 75
		}, {
			name: 'pev',
			maxIndex: 3
		}, {
			name: 'hier',
			maxIndex: 4
		}, {
			name: "list",
			maxIndex: 3
		}]
},{replaceContextDataPeriodsWith: '_'});



var sc = axDil.helpers.getCookie("s_vi");
if(sc){
	sc = sc.split("|")[1].split("[")[0];
	axDil.api.aamIdSync({
		dpid: '424',
		dpuuid: sc,
		minutesToLive: 20160
	});
};
var bbp = axDil.helpers.getCookie("blueboxpublic");
if(bbp){
	axDil.api.aamIdSync({
		dpid: '325',
		dpuuid: bbp,
		minutesToLive: 20160
	});
};